name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 12 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_SECRET }}
          user: anthonygacis
          template: classic
          base: header, activity, community, repositories, metadata
          config_padding: 6%, 20%
          config_timezone: Asia/Manila
          config_twemoji: yes
          plugin_achievements: yes
          plugin_achievements_limit: 5
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_followup: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_people: yes
          plugin_people_limit: 28
          plugin_people_size: 28
          plugin_people_types: followers, following
